[project]
name = "data-lake-management-service-slice-leading"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "getdaft[deltalake]>=0.3.15",
    "packaging>=24.2",
    "pandas>=2.2.3",
    "psycopg>=3.2.3",
]
